In [2]:
import numpy as np
x=np.arange(1,100) #np.array(range(1,100))
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [5]:
mean=np.mean(x)
print('mean:',mean)
sum=np.sum(x)
print('sum:',sum)


mean: 50.0
sum: 4950


In [8]:
y=np.sqrt(x)
print('square root:',y)

square root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.         4.12310563 4.24264069
 4.35889894 4.47213595 4.58257569 4.69041576 4.79583152 4.89897949
 5.         5.09901951 5.19615242 5.29150262 5.38516481 5.47722558
 5.56776436 5.65685425 5.74456265 5.83095189 5.91607978 6.
 6.08276253 6.164414   6.244998   6.32455532 6.40312424 6.4807407
 6.55743852 6.63324958 6.70820393 6.78232998 6.8556546  6.92820323
 7.         7.07106781 7.14142843 7.21110255 7.28010989 7.34846923
 7.41619849 7.48331477 7.54983444 7.61577311 7.68114575 7.74596669
 7.81024968 7.87400787 7.93725393 8.         8.06225775 8.1240384
 8.18535277 8.24621125 8.30662386 8.36660027 8.42614977 8.48528137
 8.54400375 8.60232527 8.66025404 8.71779789 8.77496439 8.83176087
 8.88819442 8.94427191 9.         9.05538514 9.11043358 9.16515139
 9.21954446 9.2736185  9.32737905 9.38083152 9.43398113 9.4

In [10]:
z=np.diff(x)
print('diff:',z)

diff: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [11]:
f=np.array(x+(x/2))
print(f)

[  1.5   3.    4.5   6.    7.5   9.   10.5  12.   13.5  15.   16.5  18.
  19.5  21.   22.5  24.   25.5  27.   28.5  30.   31.5  33.   34.5  36.
  37.5  39.   40.5  42.   43.5  45.   46.5  48.   49.5  51.   52.5  54.
  55.5  57.   58.5  60.   61.5  63.   64.5  66.   67.5  69.   70.5  72.
  73.5  75.   76.5  78.   79.5  81.   82.5  84.   85.5  87.   88.5  90.
  91.5  93.   94.5  96.   97.5  99.  100.5 102.  103.5 105.  106.5 108.
 109.5 111.  112.5 114.  115.5 117.  118.5 120.  121.5 123.  124.5 126.
 127.5 129.  130.5 132.  133.5 135.  136.5 138.  139.5 141.  142.5 144.
 145.5 147.  148.5]


In [3]:
t=(3,4,0,6,np.NAN,7)
print(type(t))
x=np.array(t)
print(x!=0,type(x))


<class 'tuple'>
[ True  True False  True  True  True] <class 'numpy.ndarray'>


In [49]:
y=np.array([3,4,2,6,np.NAN,7],dtype=float)
print(y,type(y))
y.dtype

[ 3.  4.  2.  6. nan  7.] <class 'numpy.ndarray'>


dtype('float64')

In [48]:
z=np.sort(np.array(t))
print(z)
z.dtype

[ 2.  3.  4.  6.  7. nan]


dtype('float64')

In [51]:
r=np.isnan(np.array(t))
print(r)
r.dtype

[False False False False  True False]


dtype('bool')

In [45]:
r.sum()

1

In [59]:
#3
import numpy as np
a,b,c=(1,3,5,9,11,18),list(range(1,7)),[7]*6
m=np.array([a,b,c])
print(m)

[[ 1  3  5  9 11 18]
 [ 1  2  3  4  5  6]
 [ 7  7  7  7  7  7]]


In [63]:
print('shape of m:',m.shape)
print('dimension:',m.ndim)

shape of m: (3, 6)
dimension: 2


In [70]:
print('transpose:',m.T)
copy=m.copy()
print('copied value :',copy)
print('size:',m.size)

transpose: [[ 1  1  7]
 [ 3  2  7]
 [ 5  3  7]
 [ 9  4  7]
 [11  5  7]
 [18  6  7]]
copied value : [[ 1  3  5  9 11 18]
 [ 1  2  3  4  5  6]
 [ 7  7  7  7  7  7]]
size: 18


In [81]:
l=np.array([0,1,2,3,4])
print(l)
r=l.repeat(3,axis=None)
print(r)
t=np.tile(l,3)
print(t)

[0 1 2 3 4]
[0 0 0 1 1 1 2 2 2 3 3 3 4 4 4]
[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [91]:
import numpy as np
d=np.array([[1, 2,3, 4, 5, 6, 7, 8, 9, 10],[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]])
print(d,d[::-1])
r=np.repeat(d,2,axis=0)
print(r)
c=np.repeat(d,2,axis=1)
print(c)

[[ 1  2  3  4  5  6  7  8  9 10]
 [10  9  8  7  6  5  4  3  2  1]] [[10  9  8  7  6  5  4  3  2  1]
 [ 1  2  3  4  5  6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [10  9  8  7  6  5  4  3  2  1]
 [10  9  8  7  6  5  4  3  2  1]]
[[ 1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10 10]
 [10 10  9  9  8  8  7  7  6  6  5  5  4  4  3  3  2  2  1  1]]


In [97]:
j=np.zeros(3)
k=np.ones(5)
l=[True,False,True]
m=np.concatenate((j,k,l),axis=None)
print(m)

[0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1.]


In [106]:
np.random.shuffle(m)
print(m)

[1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1.]


In [111]:
v=np.array([3,6,0,2,1,0])
n=np.array((v!=0))
print(v[n])

[3 6 2 1]


In [131]:
s=v[2:6]
print(s)
s1=n[1:4]
print(s1)

[0 2 1 0]
[ True False  True]


In [128]:
v=np.array([3,6,0,2,1,0])
nonzero_index=np.nonzero(v)
print(nonzero_index,v[nonzero_index])
print((v[nonzero_index]).shape)
print((np.take(v,nonzero_index)).shape)

(array([0, 1, 3, 4], dtype=int64),) [3 6 2 1]
(4,)
(1, 4)


In [141]:
#a=np.array([[0,1,2,3],[10,11,12,13]])
a=np.array([np.arange(0,4),np.arange(10,14)])
print(a)
b=np.array([[1,4,6,6],[8,3,45,2]])
print(b)
c=np.array([[1,2],[3,4]])
print(c)
j=np.concatenate((a,b),axis=1)
print(j)
j1=np.concatenate((a,b),axis=0)
print(j1)


[[ 0  1  2  3]
 [10 11 12 13]]
[[ 1  4  6  6]
 [ 8  3 45  2]]
[[1 2]
 [3 4]]
[[ 0  1  2  3  1  4  6  6]
 [10 11 12 13  8  3 45  2]]
[[ 0  1  2  3]
 [10 11 12 13]
 [ 1  4  6  6]
 [ 8  3 45  2]]
